services:
  postgres:
    image: postgres:17
    container_name: my-business-panel-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-mybusinesspaneldb}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./docker-init:/docker-entrypoint-initdb.d
      - ../my-business-panel-database:/db-scripts

  pgadmin:
    image: dpage/pgadmin4
    container_name: my-business-panel-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "8080:80"
    depends_on:
      - postgres

  redis:
    image: redis:7-alpine
    container_name: my-business-panel-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - ./redis-data:/data
    networks:
      - redis-network
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

  redis-insight:
    image: redis/redisinsight:latest
    container_name: my-business-panel-redis-insight
    restart: unless-stopped
    ports:
      - "5540:5540"
    volumes:
      - ./redis-insight-data:/data
    networks:
      - redis-network
    depends_on:
      - redis

networks:
  redis-network:
    driver: bridge
